name: dotnet_restore_and_build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: dotnet restore
      run: dotnet restore
    - name: dotnet build
      run: dotnet build --artifacts-path dotnet_build --no-restore  
    - name: create artifact
    - uses: actions/upload-artifact@v2
      with:
         name: build
         path: dotnet_build