name: dotnet_create_package

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: initialize dotnet
      uses: actions/setup-dotnet@v4
    - name: obtain artifact
      uses: actions/cache/restore@v4
      with:
        path: ./dotnet_build
        key: build
    - name: write output
      run: ls
    - name: run tests
      run: | 
        cd dotnet_build
        dotnet test --no-build