name: nuget-build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: restore
        uses: hurles/SharpExcel/blob/main/.github/workflows/dotnet_restore.yml
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test
        uses: hurles/SharpExcel/blob/main/.github/workflows/dotnet_test.yml
  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: test
        uses: hurles/SharpExcel/blob/main/.github/workflows/dotnet_package.yml