name: dotnet_restore_and_build

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: initialize dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: dotnet restore + build
      run: dotnet build "/p:Version=0.0.1-alpha${GITHUB_SHA::6}" -o "dotnet_build"
    - name: write output
      run: ls
    - name: create artifact
      uses: actions/cache@v2
      with:
         key: build
         path: dotnet_build