name: dotnet_create_package

on:
  workflow_call:
    inputs:
      version:
        description: 'the version string'
        required: true
        type: string
      projectname:
        description: 'name of project'
        required: true
        type: string
        
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: obtain artifact
      uses: actions/cache/restore@v4
      with:
        path: dotnet_pack
        key: dotnet_pack{{ github.sha }}
    - name: write output
      run: ls
    - name: create package
      run: dotnet nuget push "dotnet_pack/bin/Debug/${{ inputs.projectname }}.${{ inputs.version }}.nupkg"  --api-key $ACTIONS_ACCESSTOKEN --source "github"