name: nuget-build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch: 

jobs:
  build:
    uses: ./.github/workflows/dotnet_restore.yml@main
  test:
    needs: build
    uses: ./.github/workflows/dotnet_test.yml@main
  package:
    needs: test
    uses: ./.github/workflows/dotnet_package.yml@main