name: SharpExcel build pipeline

env:
  VERSION_STRING: 0.0.1-alpha${GITHUB_SHA::6}
  
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
    
jobs:
  build:
    uses: ./.github/workflows/dotnet_build_restore.yml
    with:
      version: $VERSION_STRING
  test:
    needs: build
    uses: ./.github/workflows/dotnet_test.yml
    with:
      projectname: SharpExcel.Tests
  package:
    needs: test
    uses: ./.github/workflows/dotnet_pack.yml
    with:
      projectname: SharpExcel
      version: $VERSION_STRING