name: dotnet_restore_and_build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: initialize dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: dotnet restore + build
      run: |
        echo "$VERSION_STRING"
        dotnet build /p:Version=$VERSION_STRING --artifacts-path "dotnet_build"
    - name: write output
      run: ls
    - name: create artifact
      uses: actions/cache@v4
      with:
         key: dotnet_build${GITHUB_SHA::6}
         path: dotnet_build