name: dotnet_create_package

on:
  workflow_call:
    inputs:
      version:
        description: 'the version string'
        required: true
        type: string
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: create models package
      run: dotnet pack SharpExcel.Models/SharpExcel.Models.csproj -o package_output/SharpExcel.Models -c Release /p:Version=${{ inputs.version }}
    - name: create package
      run: dotnet pack SharpExcel/SharpExcel.csproj -o package_output/SharpExcel -c Release /p:Version=${{ inputs.version }}
    - name: write output
      run: ls
    - name: create artifact
      uses: actions/cache@v4
      with:
        key: dotnet_pack${{ inputs.version }}
        path: package_output
