name: nuget-build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:
    
env:
    VERSION_STRING: 0.0.1-alpha${GITHUB_SHA::6}
    
jobs:
  build:
    uses: ./.github/workflows/dotnet_build_restore.yml
    with:
      version: ${{ env.VERSION_STRING }}
  test:
    needs: build
    uses: ./.github/workflows/dotnet_test.yml
    with:
      project: SharpExcel.Tests
  package:
    needs: test
    uses: ./.github/workflows/dotnet_pack.yml
    with:
      version: ${{ env.VERSION_STRING }}
      project: SharpExcel