name: SharpExcel build pipeline
  
on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - id: get-version
        shell: bash
        run: echo "version=$(date +%s)" >> $GITHUB_OUTPUT
  build:
    needs: get-version
    uses: ./.github/workflows/dotnet_build_restore.yml
    with:
      version: 0.0.1-alpha${{ needs.get-version.outputs.version }}
  test:
    needs: [ build, get-version ]
    uses: ./.github/workflows/dotnet_test.yml
    with:
      projectname: SharpExcel.Tests
  package:
    needs: [ test, get-version ]
    uses: ./.github/workflows/dotnet_pack.yml
    with:
      version: 0.0.1-alpha${{ needs.get-version.outputs.version }}
  publish:
    if: github.ref == 'refs/heads/main'      
    needs: [ package, get-version ]
    uses: ./.github/workflows/dotnet_publish.yml
    secrets: inherit
    with:
      version: 0.0.1-alpha${{ needs.get-version.outputs.version }}