name: dotnet_create_package

on:
  workflow_call:
    inputs:
      project:
        description: 'The product to run dotnet test on'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: initialize dotnet
      uses: actions/setup-dotnet@v4
    - name: obtain artifact
      uses: actions/cache/restore@v4
      with:
        path: dotnet_build
        key: dotnet_build${GITHUB_SHA::6}
    - name: write output
      run: ls
    - name: run tests
      run: | 
        cd dotnet_build
        dotnet test "bin/${{ inputs.project }}/debug/${{ inputs.project }}.dll" --no-build