name: nuget-build

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch: 

jobs:
  build:
    uses: ./.github/workflows/dotnet_build_restore.yml
  test:
    needs: build
    uses: ./.github/workflows/dotnet_test.yml
  package:
    needs: test
    uses: ./.github/workflows/dotnet_pack.yml