name: dotnet_restore_and_build

on:
  workflow_call:
    inputs:
      version:
        description: 'the version string'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: initialize dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: dotnet restore + build
      run: dotnet build /p:Version=${{ inputs.version }} --artifacts-path "dotnet_build"
    - name: write output
      run: ls
    - name: create artifact
      uses: actions/cache@v4
      with:
         key: dotnet_build${GITHUB_SHA::6}
         path: dotnet_build