name: SharpExcel build pipeline
  
on:
  release:
    types: [ released, prereleased ]

jobs:
  build:
    uses: ./.github/workflows/dotnet_build_restore.yml
    with:
      version: ${{ github.event.release.tag_name }}
  test:
    needs: [ build ]
    uses: ./.github/workflows/dotnet_test.yml
    with:
      projectname: SharpExcel.Tests
  package:
    needs: [ test ]
    uses: ./.github/workflows/dotnet_pack.yml
    with:
      version: ${{ github.event.release.tag_name }}
  publish:
    needs: [ package ]
    uses: ./.github/workflows/dotnet_publish_nuget.yml
    secrets: inherit
    with:
      version: ${{ github.event.release.tag_name }}
